//! Decoder for the PTM (Program Trace Macrocell) packet stream.
//!
//! Implements the ETMv3 PFT packet format as specified in ARM IHI0035B §4
//! (Program Flow Trace Protocol). Consumes raw bytes captured from an ETF
//! circular buffer and produces a sequence of [`PtmPacket`] values.
//!
//! ## Packet identification summary (IHI0035B Table 4.1)
//!
//! | Header byte (binary) | Value  | Packet type                       |
//! |----------------------|--------|-----------------------------------|
//! | `0000_0000`          | 0x00   | A-Sync (≥5 × 0x00 then 0x80)     |
//! | `0000_1000`          | 0x08   | I-Sync (instruction synchronization) |
//! | `0000_1100`          | 0x0C   | Trigger                           |
//! | `0111_0010`          | 0x72   | Waypoint update (+ 1-5 addr bytes)|
//! | `0111_0110`          | 0x76   | Exception return (PFTv1.1 / A only)|
//! | `0110_0110`          | 0x66   | Ignore                            |
//! | `0110_1110`          | 0x6E   | Context ID                        |
//! | `0011_1100`          | 0x3C   | VMID                              |
//! | `0100_0x10`          | 0x42/0x46 | Timestamp                      |
//! | `xxxx_xxx1` (odd)    | —      | Branch address                    |
//! | `1xxx_xxx0` (even)   | —      | Atom (P-header); Formats 1-5      |
//!
//! ## Limitations
//!
//! - Does not decode VMID, timestamp, or ContextID payload bytes (they are consumed and
//!   represented as opaque variants).
//! - Does not reconstruct full instruction traces (that requires the ELF binary).
//! - Input must start at a synchronization point (A-Sync + I-Sync sequence). Leading
//!   bytes before the first sync are discarded.
//!
//! ## Usage
//!
//! ```
//! use probe_rs::architecture::arm::component::ptm_decoder::{Decoder, PtmPacket};
//!
//! let raw_ptm_bytes: &[u8] = &[/* ... */];
//! // context_id_bytes = 0 for bare-metal targets (no OS context IDs).
//! let decoder = Decoder::new(raw_ptm_bytes, 0);
//! for packet in decoder {
//!     println!("{packet}");
//! }
//! ```

use std::fmt;

/// A decoded PTM packet.
#[derive(Debug, Clone, PartialEq, serde::Serialize)]
#[serde(tag = "type", content = "data")]
pub enum PtmPacket {
    /// Synchronization sequence complete (`0x00 × 5..N, 0x80`).
    Sync,

    /// I-Sync (instruction address sync) packet.
    ///
    /// Provides the current PC and processor state at a sync / exception boundary.
    ISync {
        /// Program Counter value (bits [31:1], bit 0 encodes Thumb state).
        pc: u32,
        /// CPSR (only the low 8 bits are typically traced: mode + T + F + I bits).
        cpsr_low8: u8,
        /// Context ID bytes (0–4 bytes depending on ETMCR.CONTEXTIDSIZE).
        context_id: u32,
    },

    /// Branch address packet (direct or indirect branch target, partially or fully qualified).
    ///
    /// The `address` field is the complete reconstructed branch target. `is_exception`
    /// is set when this is an exception entry branch. `is_link` is set when the branch
    /// is a function-call with link (BL/BLX).
    Branch {
        /// Reconstructed branch target address.
        address: u32,
        /// Set when this branch is an exception entry (e.g. IRQ, Prefetch Abort).
        is_exception: bool,
        /// Set when the branch is a function call with link (BL/BLX).
        is_link: bool,
        /// Non-secure bit from the I-Sync context before this branch.
        ns: bool,
    },

    /// P-Header (atom) packet: a run of Executed (E) / Not-executed (N) outcomes
    /// for direct conditional branches.
    Atom {
        /// True bits are Executed (branch taken), false bits are Not-executed.
        /// Bit 0 is the first branch in order.
        executed: u8,
        /// Number of valid low bits in `executed`. Always 1–6.
        count: u8,
    },

    /// Trigger packet — an ETM trigger event was signalled at this point in the trace.
    Trigger,

    /// Waypoint update — the most recent non-waypoint instruction was upgraded
    /// to a waypoint to allow full reconstruction across an exception.
    WaypointUpdate,

    /// Exception return (PFTv1.1, ARMv7-A/R only — never generated by PFTv1.0).
    ExceptionReturn,

    /// Overflow — some trace bytes were lost.
    Overflow,

    /// Context ID update (raw, un-parsed payload).
    ContextId(u32),

    /// Timestamp (raw, un-parsed payload).
    Timestamp(u64),

    /// An unknown or malformed packet header — the decoder skipped this byte.
    Unknown(u8),
}

impl fmt::Display for PtmPacket {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Sync => write!(f, "SYNC"),
            Self::ISync { pc, cpsr_low8, context_id } => write!(
                f,
                "ISYNC  pc={pc:#010x}  cpsr_low8={cpsr_low8:#04x}  ctx={context_id:#010x}"
            ),
            Self::Branch { address, is_exception, is_link, ns } => {
                write!(f, "BRANCH {address:#010x}")?;
                if *is_link { write!(f, " LINK")?; }
                if *is_exception { write!(f, " EXCEPTION")?; }
                if *ns { write!(f, " NS")?; }
                Ok(())
            }
            Self::Atom { executed, count } => {
                write!(f, "ATOM   ")?;
                for i in 0..*count {
                    let ch = if (executed >> i) & 1 == 1 { 'E' } else { 'N' };
                    write!(f, "{ch}")?;
                }
                Ok(())
            }
            Self::Trigger => write!(f, "TRIGGER"),
            Self::WaypointUpdate => write!(f, "WAYPOINT"),
            Self::ExceptionReturn => write!(f, "EXCEPTION_RETURN"),
            Self::Overflow => write!(f, "OVERFLOW"),
            Self::ContextId(id) => write!(f, "CONTEXT_ID {id:#010x}"),
            Self::Timestamp(ts) => write!(f, "TIMESTAMP {ts}"),
            Self::Unknown(b) => write!(f, "UNKNOWN  {b:#04x}"),
        }
    }
}

//─────────────────────────────────────────────────────────────────────────────
// Decoder
//─────────────────────────────────────────────────────────────────────────────

/// Decoder state tracked across packets for reconstructing branch addresses.
///
/// PTM branch address packets use the previous "address" as a base for
/// continuation bytes — only the changed high bits are transmitted.
#[derive(Debug, Clone, Default)]
struct DecoderState {
    /// Last known program counter (updated by I-Sync and fully-qualified branches).
    last_pc: u32,
    /// Number of context ID bytes expected per packet (0–4), from ETMCR.
    context_id_bytes: u8,
}

impl DecoderState {
    /// Reconstruct a branch target from a sequence of address continuation bytes.
    ///
    /// ETMv3/PTM branch address encoding (ARM DDI 0314H §4.3, IHI0035B §4.3.3):
    ///
    /// ```text
    /// Byte 0      (header):   bit[0]=1 (branch marker), bit[7]=S, bits[6:1] = A[6:1]
    /// Bytes 1..N-2 (middle):  bit[7]=S, bits[6:0] = next 7 address bits
    /// Byte N-1    (final, partial packet N<5):
    ///                         bit[7]=0, bit[6]=E (exception info follows),
    ///                         bit[5]=altISA (alternate-ISA byte follows),
    ///                         bits[4:0] = next 5 address bits
    /// Byte 4      (final, full 5-byte packet):
    ///                         bit[7]=0, bit[6]=E, bits[5:4/5:3/5:0] = ISA state
    /// ```
    ///
    /// Address bit counts per packet length:
    /// - 1-byte: 6 bits (A[6:1])
    /// - 2-byte: 6 + 5 = 11 bits (A[11:1])
    /// - 3-byte: 6 + 7 + 5 = 18 bits (A[18:1])
    /// - 4-byte: 6 + 7 + 7 + 5 = 25 bits (A[25:1])
    /// - 5-byte: 32-bit absolute address
    ///
    /// Returns `(address, is_exception, has_alt_isa, is_link)`.
    /// The caller must consume the altISA byte (if any) and exception-info bytes (if any)
    /// before continuing to decode the next packet.
    fn reconstruct_branch(&mut self, bytes: &[u8]) -> (u32, bool, bool, bool) {
        debug_assert!(!bytes.is_empty());

        // Byte 0: bits[6:1] → addr[5:0]  (6 bits representing A[6:1], with A[0] implicit)
        let mut addr: u32 = ((bytes[0] & 0x7E) >> 1) as u32;
        let mut is_exception = false;
        let mut has_alt_isa = false;
        let is_link = false;

        if bytes.len() == 5 {
            // Full 5-byte packet: bytes 1-3 are plain 7-bit address chunks;
            // byte 4 carries ISA state and exception flag.
            for (idx, &b) in bytes[1..4].iter().enumerate() {
                addr |= ((b & 0x7F) as u32) << (6 + 7 * idx);
            }
            let b4 = bytes[4];
            if b4 & 0x20 != 0 {
                // Jazelle state — bits[4:0] of byte 4 are upper address bits
                addr |= ((b4 & 0x1F) as u32) << 27;
            } else if b4 & 0x10 != 0 {
                // Thumb state
                addr |= ((b4 & 0x0F) as u32) << 27;
            } else {
                // ARM state
                addr |= ((b4 & 0x07) as u32) << 27;
            }
            is_exception = b4 & 0x40 != 0;
        } else if bytes.len() > 1 {
            // Partial packet (2–4 bytes):
            // Intermediate bytes (bytes[1..len-2]) carry 7 plain address bits each.
            // Final byte (bytes[len-1]) carries only 5 address bits (bits[4:0]);
            //   bit[6] = E (exception info follows), bit[5] = altISA byte follows.
            let last = bytes.len() - 1;
            for (idx, &b) in bytes[1..last].iter().enumerate() {
                addr |= ((b & 0x7F) as u32) << (6 + 7 * idx);
            }
            let final_b = bytes[last];
            let intermediate_count = (last - 1) as u32; // number of 7-bit middle bytes
            let final_bit_offset = 6 + 7 * intermediate_count;
            addr |= ((final_b & 0x1F) as u32) << final_bit_offset;
            is_exception = (final_b & 0x40) != 0;
            has_alt_isa   = (final_b & 0x20) != 0;
        }
        // 1-byte packet: no extra bytes — addr already has the 6-bit partial address,
        // no exception/altISA flag bits available.

        let reconstructed = if bytes.len() == 5 {
            addr | (self.last_pc & 1) // preserve Thumb bit from last_pc for full packets
        } else {
            // Partial address: reconstruct by patching only the known bits into last_pc.
            // `addr` holds A[nbits:1] in addr[nbits-1:0] (1-byte case: 6 bits,
            //  partial cases: 11/18/25 bits depending on length).
            let addr_bits: u32 = match bytes.len() {
                1 => 6,
                2 => 11,
                3 => 18,
                4 => 25,
                _ => unreachable!(),
            };
            let mask = ((1u32 << addr_bits).wrapping_sub(1)) << 1;
            (self.last_pc & !mask) | ((addr << 1) & mask)
        };

        self.last_pc = reconstructed & !1; // strip Thumb bit for state tracking
        (reconstructed, is_exception, has_alt_isa, is_link)
    }
}

//─────────────────────────────────────────────────────────────────────────────
// Public iterator
//─────────────────────────────────────────────────────────────────────────────

/// Iterator that decodes PTM/ETMv3 packets from a byte slice.
///
/// Discards all bytes until the first A-Sync + I-Sync synchronization sequence.
/// After that, yields [`PtmPacket`] values in order.
pub struct Decoder<'a> {
    /// Raw PTM byte slice being decoded.
    data: &'a [u8],
    /// Current read position within `data`.
    pos: usize,
    /// Per-packet decoder state (last PC, context-ID size).
    state: DecoderState,
    /// Whether the A-Sync + I-Sync synchronization sequence has been found.
    synced: bool,
}

impl<'a> Decoder<'a> {
    /// Create a decoder for the given raw PTM byte slice.
    ///
    /// `context_id_bytes` must match `ETMCR.CONTEXTIDSIZE` (typically 0 for bare-metal).
    pub fn new(data: &'a [u8], context_id_bytes: u8) -> Self {
        Self {
            data,
            pos: 0,
            state: DecoderState {
                last_pc: 0,
                context_id_bytes,
            },
            synced: false,
        }
    }

    fn peek(&self) -> Option<u8> {
        self.data.get(self.pos).copied()
    }

    fn consume(&mut self) -> Option<u8> {
        let b = self.data.get(self.pos).copied()?;
        self.pos += 1;
        Some(b)
    }

    fn consume_n(&mut self, n: usize) -> bool {
        if self.pos + n <= self.data.len() {
            self.pos += n;
            true
        } else {
            self.pos = self.data.len();
            false
        }
    }

    /// Scan forward for the A-Sync sequence: at least 5 `0x00` bytes followed by `0x80`.
    /// Returns true if found and `pos` is now just past the `0x80`.
    fn scan_for_async(&mut self) -> bool {
        let d = &self.data[self.pos..];
        // Find a run of ≥5 zeros followed by 0x80.
        let mut i = 0;
        while i < d.len() {
            // Find 0x80
            if let Some(pos80) = d[i..].iter().position(|&b| b == 0x80) {
                let abs = i + pos80;
                // Count leading zeros before this 0x80
                let zeros = d[..abs].iter().rev().take_while(|&&b| b == 0x00).count();
                if zeros >= 5 {
                    self.pos += abs + 1;
                    return true;
                }
                i = abs + 1;
            } else {
                break;
            }
        }
        self.pos = self.data.len();
        false
    }

    /// Parse an I-Sync packet body (IHI0035B §5.6.2).
    ///
    /// Layout after the `0x04` header:
    ///   [context_id_bytes bytes] [1 byte cpsr_low8] [1..5 address bytes]
    fn parse_isync(&mut self) -> Option<PtmPacket> {
        // IHI0035B §4.2 I-sync packet order (matches ptm2human isync decoder):
        //   1 byte  : header (already consumed by caller)
        //   4 bytes : instruction address, raw little-endian 32-bit
        //             bit[0] of the address word = T bit (Thumb state)
        //   1 byte  : info byte (reason[6:5], NS[3], AltIS[2], Hyp[1])
        //   0-5 bytes: cycle count (cycle-accurate mode only; not yet supported)
        //   0-4 bytes: context ID (size from ETMCR.ContextIDSize)

        // Read 4-byte raw LE address.
        let mut pc: u32 = 0;
        for i in 0..4 {
            pc |= (self.consume()? as u32) << (8 * i);
        }

        // Read info byte (stored in cpsr_low8 field for caller convenience).
        let cpsr_low8 = self.consume()?;

        // Read context ID bytes (LE).
        let ctx_bytes = self.state.context_id_bytes as usize;
        let mut context_id: u32 = 0;
        for i in 0..ctx_bytes {
            context_id |= (self.consume()? as u32) << (8 * i);
        }

        self.state.last_pc = pc & !1;

        Some(PtmPacket::ISync {
            pc,
            cpsr_low8,
            context_id,
        })
    }

    /// Parse a branch address packet (IHI0035B §4.3.3).
    ///
    /// The header byte is the first byte of the packet (odd byte — bit 0 set).
    /// Up to 4 more continuation bytes follow.  For partial packets (< 5 bytes) the
    /// final byte may set bit[6] (exception-info bytes follow) and bit[5] (altISA byte
    /// follows); those trailing bytes are consumed here so the caller always sees clean
    /// packet boundaries.
    fn parse_branch(&mut self, header: u8) -> Option<PtmPacket> {
        let mut addr_bytes = vec![header];
        // bit[7]=1 means another address byte follows; bit[7]=0 means last address byte.
        while addr_bytes.last().map(|b| b & 0x80 != 0).unwrap_or(false)
            && addr_bytes.len() < 5
        {
            addr_bytes.push(self.consume()?);
        }

        let (address, is_exception, has_alt_isa, is_link) =
            self.state.reconstruct_branch(&addr_bytes);

        // Consume the alternate-ISA byte if flagged (ARM DDI 0314H §4.3.2).
        // It always precedes the exception-info bytes.
        if has_alt_isa {
            self.consume()?; // one altISA byte, no further continuation
        }

        // Consume exception-info bytes if flagged (ARM DDI 0314H §4.3.3).
        // Each byte has bit[5]=S (continuation): 1 = another exception-info byte follows.
        if is_exception {
            loop {
                let exc = self.consume()?;
                if exc & 0x20 == 0 {
                    break; // S=0 → last exception-info byte
                }
            }
        }

        let ns = false;
        Some(PtmPacket::Branch { address, is_exception, is_link, ns })
    }

    /// Decode an atom (P-header) byte (IHI0035B Table 4.3).
    ///
    /// All atom packets have bit7=1 and bit0=0. The format (atom count) is
    /// identified by the highest set bit among bits[6:2]:
    ///
    /// | Highest set bit | Format | Count |
    /// |-----------------|--------|-------|
    /// | bit6            | 5      | 5     |
    /// | bit5            | 4      | 4     |
    /// | bit4            | 3      | 3     |
    /// | bit3            | 2      | 2     |
    /// | bit2            | 1      | 1     |
    /// | none (bits 6:2 all zero) | 0 | reserved |
    ///
    /// Atom N (0 = oldest) occupies bit[count - N] of the byte.
    /// F=0 ↔ E (Executed / branch taken); F=1 ↔ N (Not-executed).
    /// In `PtmPacket::Atom`, bit N of `executed` is 1 when atom N is an E atom.
    fn decode_atom(byte: u8) -> PtmPacket {
        let cnt: u8 = if byte & 0x40 != 0 {
            5
        } else if byte & 0x20 != 0 {
            4
        } else if byte & 0x10 != 0 {
            3
        } else if byte & 0x08 != 0 {
            2
        } else if byte & 0x04 != 0 {
            1
        } else {
            // Format 0 (`1000_00x0`) is reserved.
            return PtmPacket::Unknown(byte);
        };

        // Atom N (0=oldest, cnt-1=newest) is at bit position (cnt - N) in the byte.
        // F=0 → E → set the corresponding bit in `executed`.
        let mut executed: u8 = 0;
        for n in 0..cnt {
            let bit_pos = cnt - n;
            if byte & (1 << bit_pos) == 0 {
                executed |= 1 << n;
            }
        }
        PtmPacket::Atom { executed, count: cnt }
    }

    /// Consume and parse a timestamp packet body (IHI0035B §4).
    ///
    /// Variable-length: each byte has C-bit (bit7) as continuation.
    fn parse_timestamp(&mut self) -> PtmPacket {
        let mut ts: u64 = 0;
        let mut shift = 0u64;
        loop {
            let b = match self.consume() {
                Some(b) => b,
                None => break,
            };
            ts |= ((b & 0x7F) as u64) << shift;
            shift += 7;
            if b & 0x80 == 0 || shift >= 56 {
                break;
            }
        }
        PtmPacket::Timestamp(ts)
    }

    /// Consume a waypoint update packet body (IHI0035B §4).
    ///
    /// The waypoint update header (0x72) is followed by 1-5 address bytes.
    /// These use bit7 as continuation (the same encoding as I-sync address bytes),
    /// unlike branch address packets which use bit0.
    fn parse_waypoint_update(&mut self) -> Option<PtmPacket> {
        // Consume bytes until the continuation bit (bit7) is clear, up to 5 bytes.
        let mut count = 0usize;
        loop {
            let b = self.consume()?;
            count += 1;
            if b & 0x80 == 0 || count >= 5 {
                break;
            }
        }
        Some(PtmPacket::WaypointUpdate)
    }

    /// Consume a variable-length context ID packet body.
    fn parse_context_id(&mut self) -> PtmPacket {
        let n = self.state.context_id_bytes as usize;
        let mut id = 0u32;
        for i in 0..n {
            if let Some(b) = self.consume() {
                id |= (b as u32) << (8 * i);
            }
        }
        PtmPacket::ContextId(id)
    }
}

impl Iterator for Decoder<'_> {
    type Item = PtmPacket;

    fn next(&mut self) -> Option<PtmPacket> {
        loop {
            // Synchronize on the A-Sync sequence before emitting any packets.
            if !self.synced {
                if !self.scan_for_async() {
                    return None;
                }
                self.synced = true;
                return Some(PtmPacket::Sync);
            }

            let header = self.consume()?;

            // IHI0035B §5.4 — packet identification.
            // Priority order: branch (bit 0 set) > specific well-known headers > p-header.
            let packet = if header & 0x01 != 0 {
                // Odd byte → branch address packet.
                self.parse_branch(header)?
            } else {
                match header {
                    // A-Sync / re-sync: leading zeros + 0x80.
                    0x00 => {
                        while self.peek() == Some(0x00) {
                            self.consume();
                        }
                        if self.peek() == Some(0x80) {
                            self.consume();
                            PtmPacket::Sync
                        } else {
                            continue;
                        }
                    }

                    // I-Sync (IHI0035B Table 4.1: 0x08)
                    0x08 => self.parse_isync()?,

                    // Trigger (Table 4.1: b0000_1100 = 0x0C)
                    0x0C => PtmPacket::Trigger,

                    // Waypoint update (Table 4.1: b0111_0010 = 0x72) + 1-5 address bytes
                    0x72 => self.parse_waypoint_update()?,

                    // Exception return (Table 4.1: b0111_0110 = 0x76)
                    // Note: PFTv1.0 ARMv7-A never generates this; PFTv1.1 does.
                    0x76 => PtmPacket::ExceptionReturn,

                    // Overflow (ETM convention: 0x70; not in Table 4.1 but widely used)
                    0x70 => PtmPacket::Overflow,

                    // Context ID (Table 4.1: b0110_1110 = 0x6E)
                    0x6E => self.parse_context_id(),

                    // Timestamp (Table 4.1: b0100_0x10 = 0x42/0x46, mask 0xFB)
                    b if b & 0xFB == 0x42 => self.parse_timestamp(),

                    // VMID (Table 4.1: b0011_1100 = 0x3C), 1 byte payload — discard
                    0x3C => {
                        self.consume_n(1);
                        continue
                    }

                    // Ignore (Table 4.1: b0110_0110 = 0x66) — no payload
                    0x66 => continue,

                    // Atom packets (Table 4.1: b1xxx_xxx0): bit7=1, bit0=0
                    b if b & 0x81 == 0x80 => Self::decode_atom(b),

                    // Unknown / undefined
                    b => PtmPacket::Unknown(b),
                }
            };

            return Some(packet);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Minimal A-Sync: 5× 0x00 followed by 0x80.
    fn async_seq() -> Vec<u8> {
        let mut v = vec![0x00u8; 5];
        v.push(0x80);
        v
    }

    fn decode_all(data: &[u8], ctx: u8) -> Vec<PtmPacket> {
        Decoder::new(data, ctx).collect()
    }

    // ── Synchronisation ─────────────────────────────────────────────────────

    #[test]
    fn decode_sync_only() {
        let data = async_seq();
        let mut dec = Decoder::new(&data, 0);
        assert_eq!(dec.next(), Some(PtmPacket::Sync));
        assert_eq!(dec.next(), None);
    }

    /// Any bytes before the first A-Sync are silently discarded.
    #[test]
    fn decode_junk_before_sync_is_discarded() {
        let mut data = vec![0xAB, 0xCD, 0xFF];
        data.extend(async_seq());
        data.push(0x0C); // Trigger
        let pkts = decode_all(&data, 0);
        assert_eq!(pkts, vec![PtmPacket::Sync, PtmPacket::Trigger]);
    }

    /// A second A-Sync mid-stream emits a second Sync packet.
    #[test]
    fn decode_resync_mid_stream() {
        let mut data = async_seq();
        data.push(0x0C); // Trigger
        data.extend(async_seq());
        data.push(0x0C); // Trigger
        let pkts = decode_all(&data, 0);
        assert_eq!(
            pkts,
            vec![
                PtmPacket::Sync,
                PtmPacket::Trigger,
                PtmPacket::Sync,
                PtmPacket::Trigger
            ]
        );
    }

    // ── Misc single-byte packets ─────────────────────────────────────────────

    #[test]
    fn decode_trigger() {
        let mut data = async_seq();
        data.push(0x0C); // 0b0000_1100
        assert_eq!(
            decode_all(&data, 0),
            vec![PtmPacket::Sync, PtmPacket::Trigger]
        );
    }

    #[test]
    fn decode_overflow() {
        let mut data = async_seq();
        data.push(0x70);
        assert_eq!(
            decode_all(&data, 0),
            vec![PtmPacket::Sync, PtmPacket::Overflow]
        );
    }

    #[test]
    fn decode_exception_return() {
        let mut data = async_seq();
        data.push(0x76); // PFTv1.1 exception return
        assert_eq!(
            decode_all(&data, 0),
            vec![PtmPacket::Sync, PtmPacket::ExceptionReturn]
        );
    }

    /// Ignore (0x66) produces no packet.
    #[test]
    fn decode_ignore_is_silent() {
        let mut data = async_seq();
        data.push(0x66); // ignore
        data.push(0x0C); // trigger — proves the first byte was consumed cleanly
        assert_eq!(
            decode_all(&data, 0),
            vec![PtmPacket::Sync, PtmPacket::Trigger]
        );
    }

    // ── I-sync ───────────────────────────────────────────────────────────────

    /// Single-address-byte I-sync, no context ID.
    ///
    /// Spec order: header, 4 addr bytes (LE), info byte.
    /// addr LE = [0x10, 0x00, 0x00, 0x00] → pc = 0x10.
    #[test]
    fn decode_isync_no_context_id() {
        let mut data = async_seq();
        data.extend([0x08, 0x10, 0x00, 0x00, 0x00, 0xD3]);
        let pkts = decode_all(&data, 0);
        assert_eq!(pkts.len(), 2);
        assert_eq!(pkts[0], PtmPacket::Sync);
        assert_eq!(
            pkts[1],
            PtmPacket::ISync { pc: 0x10, cpsr_low8: 0xD3, context_id: 0 }
        );
    }

    /// I-sync with a 4-byte context ID.
    #[test]
    fn decode_isync_with_context_id() {
        let mut data = async_seq();
        // header, addr bytes (LE for pc=0x10), info byte, context_id bytes (LE)
        data.extend([0x08, 0x10, 0x00, 0x00, 0x00, 0xD3, 0x78, 0x56, 0x34, 0x12]);
        let pkts = decode_all(&data, 4); // context_id_bytes = 4
        assert_eq!(
            pkts[1],
            PtmPacket::ISync { pc: 0x10, cpsr_low8: 0xD3, context_id: 0x12345678 }
        );
    }

    // ── Context ID ───────────────────────────────────────────────────────────

    #[test]
    fn decode_context_id_packet() {
        let mut data = async_seq();
        data.extend([0x6E, 0x78, 0x56, 0x34, 0x12]); // header + 4 payload bytes
        let pkts = decode_all(&data, 4);
        assert_eq!(pkts[1], PtmPacket::ContextId(0x12345678));
    }

    // ── Timestamp ───────────────────────────────────────────────────────────

    /// Single-byte timestamp value = 7.
    #[test]
    fn decode_timestamp_single_byte() {
        let mut data = async_seq();
        data.extend([0x42, 0x07]); // header 0x42; value byte 0x07 (bit7=0 → last, value=7)
        let pkts = decode_all(&data, 0);
        assert_eq!(pkts[1], PtmPacket::Timestamp(7));
    }

    /// Multi-byte timestamp with continuation bits.
    /// Bytes: 0x95 (bit7=1, val=0x15=21), 0x01 (bit7=0, val=1)
    /// ts = 21 | (1 << 7) = 21 | 128 = 149
    #[test]
    fn decode_timestamp_multi_byte() {
        let mut data = async_seq();
        data.extend([0x42, 0x95, 0x01]); // 0x95: C=1 bits[6:0]=0x15; 0x01: C=0 bits[6:0]=1
        // ts = 0x15 | (1 << 7) = 21 | 128 = 149
        let pkts = decode_all(&data, 0);
        assert_eq!(pkts[1], PtmPacket::Timestamp(149));
    }

    /// Timestamp header 0x46 (R-bit set indicates clock change) is also valid.
    #[test]
    fn decode_timestamp_r_bit_variant() {
        let mut data = async_seq();
        data.extend([0x46, 0x05]);
        let pkts = decode_all(&data, 0);
        assert_eq!(pkts[1], PtmPacket::Timestamp(5));
    }

    // ── Waypoint update ──────────────────────────────────────────────────────

    #[test]
    fn decode_waypoint_update() {
        let mut data = async_seq();
        data.extend([0x72, 0x20]); // header + 1 addr byte (bit7=0 → last)
        let pkts = decode_all(&data, 0);
        assert_eq!(pkts[1], PtmPacket::WaypointUpdate);
    }

    // ── Branch address ───────────────────────────────────────────────────────

    /// 2-byte branch with no exception: [0x81, 0x01] → address 0x80.
    ///
    /// byte[0]=0x81: bit[7]=1 (continuation), addr = (0x81 & 0x7E)>>1 = 0.
    /// byte[1]=0x01: bit[7]=0 (final), bit[6]=0 (no exception), bits[4:0]=0x01.
    ///   addr |= (0x01 & 0x1F) << 6 = 0x40.
    ///   addr_bits=11, mask=0x0FFE → address = (0 & ~0x0FFE) | (0x40<<1 & 0x0FFE) = 0x80.
    #[test]
    fn decode_branch_two_bytes() {
        let mut data = async_seq();
        data.extend([0x81, 0x01]);
        let pkts = decode_all(&data, 0);
        assert!(
            matches!(pkts[1], PtmPacket::Branch { address: 0x80, is_exception: false, .. }),
            "got {:?}",
            pkts[1]
        );
    }

    /// 2-byte branch with exception bit set: exception-info byte must be consumed
    /// and the next valid packet must decode without producing UNKNOWN.
    ///
    /// byte[0]=0xfd: continuation, addr = (0xfd & 0x7E)>>1 = 0x3E.
    /// byte[1]=0x43: final, bit[6]=1 (exception!), bits[4:0]=0x03.
    ///   addr |= 0x03 << 6 = 0xC0 → addr=0xFE.
    ///   address = 0 | (0xFE<<1 & 0xFFE) = 0x1FC.
    /// byte 0x1c: exception-info byte, S=0 → consumed, no Unknown emitted.
    /// byte 0x0C: Trigger → decoded correctly.
    #[test]
    fn decode_branch_two_bytes_with_exception_info() {
        let mut data = async_seq();
        data.extend([0xfd, 0x43, 0x1c, 0x0C]); // branch + exc-info + trigger
        let pkts = decode_all(&data, 0);
        assert_eq!(pkts.len(), 3, "expected Sync + Branch + Trigger, got {pkts:?}");
        assert!(
            matches!(pkts[1], PtmPacket::Branch { address: 0x1fc, is_exception: true, .. }),
            "expected exception branch at 0x1fc, got {:?}", pkts[1]
        );
        assert_eq!(pkts[2], PtmPacket::Trigger, "got {:?}", pkts[2]);
    }

    /// 2-byte branch with altISA only (bit[5]=1, bit[6]=0): altISA byte consumed,
    /// exception-info NOT consumed.
    ///
    /// final byte = 0x23 = 0010_0011: bit[6]=0, bit[5]=1 (altISA), bits[4:0]=0x03.
    /// addr |= 0x03 << 6 = 0xC0 → addr = 0x3E | 0xC0 = 0xFE → address = 0x1FC.
    /// 0xAB: altISA byte (consumed silently).
    /// 0x0C: Trigger → decoded correctly.
    #[test]
    fn decode_branch_two_bytes_with_alt_isa() {
        let mut data = async_seq();
        // byte[0]=0x9d = 10011101: bit7=1(cont), bits[6:1]=(0x9d&0x7E)>>1=(0x1C)>>1=0x0E=0b001110
        // addr = 0x0E
        // byte[1]=0x23 = 00100011: bit7=0(final), bit6=0(no exc), bit5=1(altISA), bits[4:0]=0x03
        //   addr |= 0x03 << 6 = 0xC0 → addr = 0x0E | 0xC0 = 0xCE
        //   address = (0 & ~0xFFE) | (0xCE<<1 & 0xFFE) = (0x19C & 0xFFE) = 0x19C
        data.extend([0x9d, 0x23, 0xAB, 0x0C]); // branch + altISA byte + trigger
        let pkts = decode_all(&data, 0);
        assert_eq!(pkts.len(), 3, "expected Sync + Branch + Trigger, got {pkts:?}");
        assert!(
            matches!(pkts[1], PtmPacket::Branch { is_exception: false, .. }),
            "unexpected exception flag, got {:?}", pkts[1]
        );
        assert_eq!(pkts[2], PtmPacket::Trigger, "altISA byte was not consumed, got {:?}", pkts[2]);
    }

    /// 2-byte branch with both altISA and exception set: altISA byte consumed first,
    /// then exception-info byte, leaving the next packet clean.
    ///
    /// final byte = 0x63 = 0110_0011: bit[6]=1(exc), bit[5]=1(altISA), bits[4:0]=0x03.
    #[test]
    fn decode_branch_two_bytes_with_alt_isa_and_exception() {
        let mut data = async_seq();
        // byte[0]=0x9d, byte[1]=0x63 (bit6=exc, bit5=altISA, bits[4:0]=0x03)
        data.extend([0x9d, 0x63, 0xAB, 0x1c, 0x0C]); // branch + altISA + exc-info + trigger
        let pkts = decode_all(&data, 0);
        assert_eq!(pkts.len(), 3, "expected Sync + Branch + Trigger, got {pkts:?}");
        assert!(
            matches!(pkts[1], PtmPacket::Branch { is_exception: true, .. }),
            "expected exception branch, got {:?}", pkts[1]
        );
        assert_eq!(pkts[2], PtmPacket::Trigger, "trailing bytes not consumed, got {:?}", pkts[2]);
    }

    /// Exception-info bytes with S-bit=1 (continuation): decoder must consume
    /// multiple exception-info bytes before returning to normal stream.
    #[test]
    fn decode_branch_exception_info_multi_byte() {
        let mut data = async_seq();
        // 2-byte branch with exception flag
        // byte[1]=0x43: bit[6]=1 (exception), bits[4:0]=0x03
        // Exception info: 0x3C (S=1, another byte follows), 0x04 (S=0, last)
        data.extend([0xfd, 0x43, 0x3c, 0x04, 0x0C]); // branch + 2 exc-info + trigger
        let pkts = decode_all(&data, 0);
        assert_eq!(pkts.len(), 3, "expected Sync + Branch + Trigger, got {pkts:?}");
        assert!(
            matches!(pkts[1], PtmPacket::Branch { is_exception: true, .. }),
            "expected exception branch, got {:?}", pkts[1]
        );
        assert_eq!(pkts[2], PtmPacket::Trigger, "multi-byte exc-info not consumed, got {:?}", pkts[2]);
    }

    /// 1-byte branch: [0x01] → single byte (bit[7]=0), no exception possible.
    /// Per IHI0035B Table 4.6: bit[7]=0 in byte 0 means no more address bytes
    /// and no exception information bytes can follow.
    /// addr = (0x01 & 0x7E)>>1 = 0 → address = 0 (with last_pc=0).
    #[test]
    fn decode_branch_single_byte() {
        let mut data = async_seq();
        data.push(0x01); // bit[7]=0 → last (single byte), bit[0]=1 → branch header
        let pkts = decode_all(&data, 0);
        assert!(
            matches!(pkts[1], PtmPacket::Branch { address: 0, is_exception: false, .. }),
            "got {:?}",
            pkts[1]
        );
    }

    // ── Atoms (all 5 formats) ────────────────────────────────────────────────
    //
    // IHI0035B Table 4.3: atom header = `1xxx_xxx0` (bit7=1, bit0=0).
    // The highest set bit among bits[6:2] gives the format (count):
    //   bit6 → Format 5 (5 atoms at bits[5:1])
    //   bit5 → Format 4 (4 atoms at bits[4:1])
    //   bit4 → Format 3 (3 atoms at bits[3:1])
    //   bit3 → Format 2 (2 atoms at bits[2:1])
    //   bit2 → Format 1 (1 atom at bit1)
    //
    // F=0 in each bit position means E (Executed/taken); F=1 means N (Not-executed).
    // Atom N=0 is oldest; in `PtmPacket::Atom` bit N of `executed` is 1 when atom N is E.

    #[test]
    fn decode_atom_format1_single_e() {
        // 0x84 = 1000_0100: cnt=1, atom0 at bit1=0 → E
        let mut data = async_seq();
        data.push(0x84);
        assert_eq!(
            decode_all(&data, 0)[1],
            PtmPacket::Atom { executed: 0b0000_0001, count: 1 }
        );
    }

    #[test]
    fn decode_atom_format1_single_n() {
        // 0x86 = 1000_0110: cnt=1, atom0 at bit1=1 → N
        let mut data = async_seq();
        data.push(0x86);
        assert_eq!(
            decode_all(&data, 0)[1],
            PtmPacket::Atom { executed: 0b0000_0000, count: 1 }
        );
    }

    #[test]
    fn decode_atom_format2_both_e() {
        // 0x88 = 1000_1000: cnt=2, bits[2:1]=00 → both E
        let mut data = async_seq();
        data.push(0x88);
        assert_eq!(
            decode_all(&data, 0)[1],
            PtmPacket::Atom { executed: 0b0000_0011, count: 2 }
        );
    }

    #[test]
    fn decode_atom_format2_both_n() {
        // 0x8E = 1000_1110: cnt=2, bits[2:1]=11 → both N
        let mut data = async_seq();
        data.push(0x8E);
        assert_eq!(
            decode_all(&data, 0)[1],
            PtmPacket::Atom { executed: 0b0000_0000, count: 2 }
        );
    }

    #[test]
    fn decode_atom_format2_e_then_n() {
        // 0x8A = 1000_1010: cnt=2, atom0 at bit2=0 → E; atom1 at bit1=1 → N
        let mut data = async_seq();
        data.push(0x8A);
        assert_eq!(
            decode_all(&data, 0)[1],
            PtmPacket::Atom { executed: 0b0000_0001, count: 2 }
        );
    }

    #[test]
    fn decode_atom_format3_all_e() {
        // 0x90 = 1001_0000: cnt=3, bits[3:1]=000 → all E
        let mut data = async_seq();
        data.push(0x90);
        assert_eq!(
            decode_all(&data, 0)[1],
            PtmPacket::Atom { executed: 0b0000_0111, count: 3 }
        );
    }

    #[test]
    fn decode_atom_format3_all_n() {
        // 0x9E = 1001_1110: cnt=3, bits[3:1]=111 → all N
        let mut data = async_seq();
        data.push(0x9E);
        assert_eq!(
            decode_all(&data, 0)[1],
            PtmPacket::Atom { executed: 0b0000_0000, count: 3 }
        );
    }

    #[test]
    fn decode_atom_format3_mixed_n_e_n() {
        // 0x9A = 1001_1010: cnt=3
        // atom0 at bit3=1 → N; atom1 at bit2=0 → E; atom2 at bit1=1 → N
        let mut data = async_seq();
        data.push(0x9A);
        assert_eq!(
            decode_all(&data, 0)[1],
            PtmPacket::Atom { executed: 0b0000_0010, count: 3 }
        );
    }

    #[test]
    fn decode_atom_format4_all_e() {
        // 0xA0 = 1010_0000: cnt=4, bits[4:1]=0000 → all E
        let mut data = async_seq();
        data.push(0xA0);
        assert_eq!(
            decode_all(&data, 0)[1],
            PtmPacket::Atom { executed: 0b0000_1111, count: 4 }
        );
    }

    #[test]
    fn decode_atom_format4_all_n() {
        // 0xBE = 1011_1110: cnt=4, bits[4:1]=1111 → all N
        let mut data = async_seq();
        data.push(0xBE);
        assert_eq!(
            decode_all(&data, 0)[1],
            PtmPacket::Atom { executed: 0b0000_0000, count: 4 }
        );
    }

    #[test]
    fn decode_atom_format5_all_e() {
        // 0xC0 = 1100_0000: cnt=5, bits[5:1]=00000 → all E
        let mut data = async_seq();
        data.push(0xC0);
        assert_eq!(
            decode_all(&data, 0)[1],
            PtmPacket::Atom { executed: 0b0001_1111, count: 5 }
        );
    }

    #[test]
    fn decode_atom_format5_all_n() {
        // 0xFE = 1111_1110: cnt=5, bits[5:1]=11111 → all N
        let mut data = async_seq();
        data.push(0xFE);
        assert_eq!(
            decode_all(&data, 0)[1],
            PtmPacket::Atom { executed: 0b0000_0000, count: 5 }
        );
    }
}
